[build]
  # Build Tailwind CSS on deployment
  publish = "."
  command = "npm run build"

[dev]
  # Optional: command to run a local dev server when using `netlify dev`
  command = "npx http-server -p 8888"

[context.production.environment]
  NODE_VERSION = "18"
